export { default as TimeSlotModal } from './time-slot/CreateModal.vue'
export { default as ServiceItem } from './Item.vue'
export { default as UpdateServiceModal } from './UpdateModal.vue'
export { default as AddServiceModal } from './AddModal.vue'
export { default as Add } from './Add.vue'
